# .github/workflows/main.yml initial file

name: Python application test with Github Actions

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest pytest-cov
    - name: Lint with pylint
      run: |
        pylint **/*.py || exit_code=$?
        if [ $exit_code -gt 9 ]; then
          exit $exit_code
        fi
    - name: Test with pytest
      run: |
        pytest --cov=./ --cov-report=xml
        coverage=$(grep -Po 'line-rate="\K[^"]*' coverage.xml)
        coverage=$(echo "scale=2; $coverage * 100" | bc)
        if (( $(echo "$coverage < 70" | bc -l) )); then
          echo "Code coverage is less than 70%"
          exit 1
        fi